name: Build and release

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Part of the version to increase'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: golang:1.20
    steps:
      - name: Checkout release repository
        uses: actions/checkout@v3
        with:
          path: reva-release
      - name: Bump version
        run: |
          cd reva-release
          git config --local user.email "cernbox-admins@cern.ch"
          git config --local user.name "cernbox-admins[bot]"
          ./bumpversion.sh ${{ github.event.inputs.part }}
          git add VERSION && git commit -m "v$(cat VERSION)" && git tag -a "v$(cat VERSION)" -m "$(cat VERSION)"
          echo "version=$(cat VERSION)" >> $GITHUB_ENV
      - name: Push version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          directory: reva-release

      - name: Checkout reva repository
        uses: actions/checkout@v3
        with:
          repository: cernbox/reva
          path: reva
      - name: Build reva
        run: |
          cd reva
          make reva revad
      - name: Create reva release
        run: |
          mkdir release
          cp reva/cmd/reva/reva release/reva && cp reva/cmd/revad/revad release/revad
          tar -C release -czf release/reva-${{ env.version }}.tar.gz reva revad
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: release/reva-${{ env.version }}.tar.gz
          name: Version ${{ env.version }}
          tag_name: v${{ env.version }}
        
